[package]
name = "real-number-game"
version = "0.1"
lean_version = "leanprover-community/lean:3.8.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "66cc29804344de86894d440d10167bb68c2cca83"}
