[package]
name = "real-number-game"
version = "0.1"
lean_version = "leanprover-community/lean:3.17.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "e4ecf146efe15a9840a8b8e5dcb1ef8525640eb1"}
