[package]
name = "real-number-game"
version = "0.1"
lean_version = "leanprover-community/lean:3.16.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "26918a05936335a46944c7a1fadeefcdb7224f97"}
